version: 1.0.{build}
image: Visual Studio 2013
environment:
  matrix:
  - COMPILER: "visual"
    CONFIGURATION: "Release"
    PLATFORM: "x64"
  - COMPILER: "visual"
    CONFIGURATION: "Release"
    PLATFORM: "Win32"

install:
  - ECHO Installing %COMPILER% %PLATFORM% %CONFIGURATION%
  - git submodule init third-party/Processlib
  - git submodule update
  - git submodule foreach "git checkout cmake"
  - MKDIR build
  - cd build
  - ps: Start-FileDownload 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/oscats/gsl-1.15-dev-win64.zip'
  - 7z.exe e gsl-1.15-dev-win64.zip -o"c:\Program Files\gsl-1.5-dev-win64"
 
build_script:
  - ECHO *** &&
      ECHO Building %COMPILER% %PLATFORM% %CONFIGURATION% &&
      ECHO ***
  - cd build
  - cmake -G"Visual Studio 12 2013 Win64" -DLIMACAMERA_ENABLE_SIMULATOR=1 ..
    
    

test_script:
  - ECHO *** &&
      ECHO Testing %COMPILER% %PLATFORM% %CONFIGURATION% &&
      ECHO ***
